### ISSUE TITLE
Update the guide

### ISSUE THREAD

**Issue by upadsamay387** [aaalgo/hyperv2hosts#2]
Hello! I had a hard time trying to get the script to work as it wouldn't ping the right VM when manually running it without using the --name argument, and even when running the script using the argument, it would only add a blank list to the hosts file.

After an hour of debugging, I figured out that I needed to install "linux-azure" on my Ubuntu VM
(footnote 5 on https://learn.microsoft.com/en-us/windows-server/virtualization/hyper-v/supported-ubuntu-virtual-machines-on-hyper-v)

Lastly, when setting up Task Scheduler, I would still get the blank IP Address fields when restarting my VM. To fix this, I had to add a few seconds of delay, and I had to change the --host-fmt argument to "--name myvmname" for it to work properly

Having these listed on the readme would be pretty helpful for anyone else who needs this script

**Comment by aaalgo** [comment]
Thanks for the tips, I've incorporated it to the README.
